### ISSUE TITLE
Write [short] chapter on MoFo implementation of git-flow.

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/MoFo-Engineering-Handbook#47]
![image](https://cloud.githubusercontent.com/assets/25260/6260599/23a6ccf8-b796-11e4-95f8-b8bb25408213.png)

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by alicoding** [comment]
It might be easy to adopt this sooner since we just started working on this repo?

@toolness @simonwex @jbuck @gesa @mmmavis ?

**Comment by mmmavis** [comment]
agree, let's create a `develop` branch and make that the default branch on https://github.com/mozilla/teach.webmaker.org.

**Comment by gesa** [comment]
On it

**Comment by gesa** [comment]
Done. develop is now the default branch on teach, let's all make sure to branch and PR off that.

**Comment by mmmavis** [comment]
:dancers: okie dokie

**Comment by alicoding** [comment]
Let's also create a gh-pages where we can check our stuff every time we tag on production. I think we can automate this by running something like 'gulp prod' which should tag things to master branch and push **dist** directory to gh-pages

**Comment by toolness** [comment]
Hey out of curiosity, have we ever considered Git*Hub* Flow?

http://scottchacon.com/2011/08/31/github-flow.html

**Comment by simonwex** [comment]
The biggest implications that Github flow would have on us are:

<blockquote>1) anything in the master branch is deployable</blockquote>
and
<blockquote>6) deploy immediately after review</blockquote>

Our current deployment strategy and our product strategy over the next few months doesn't fit with this, and hence our ability to do actual hotfixes is actually quite important. 

This isn't true across all projects. I suspect that we could have an always-deployable `master` on id.webmaker.org and the Teach site. Production webmaker.org on the other hand will likely diverge from what we commonly see on our development branches. What would our flow look like to update the webmaker.org homepage?

**Comment by simonwex** [comment]
@jbuck from a devops perspective, changing our system so we don't require tags, but instead we deploy-on-merge is something is also something you'd need to do in order for us to embrace this simpler system. 

I'll also say, if we can get there, Github Flow is more desirable and I generally agree with Scott Chacon.

**Comment by jbuck** [comment]
At Whistler we decided to not continue working on the handbook
